# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6f128d07ffe2c0338d0c3327fa13ca9fbf5b56e4603b1846300de0093a817fa057dcfa56b7227e4bd8904332e5e995b610685afc275d1563dd94cf07d11ec0

test:
  secret_key_base: 4ec626d391b330bfc7be51ab334a9a029bc176954b7434a7a69c18ddccc5c3a9bb1f2454fd5688d6bed64e6d70dd883581f66a0971745f793516d6d0845ef6e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
